// ============================================================
// MIS VALES — Mock Data (datos ficticios de demostración)
// ============================================================
import type {
  KpiCardData,
  Sucursal,
  Solicitud,
  AlertItem,
  Distribuidor,
  ActivityItem,
  LoanChartData,
  RelacionDonutData,
  NavNotification,
} from "./types";

// ── KPI Cards ─────────────────────────────────────────────
export const kpiData: KpiCardData[] = [
  {
    id: "sucursales",
    title: "Total Sucursales",
    value: 12,
    change: 0,
    icon: "building",
    color: "blue",
  },
  {
    id: "distrib-activas",
    title: "Distribuidoras Activas",
    value: 348,
    change: 4.2,
    icon: "users",
    color: "green",
  },
  {
    id: "distrib-suspendidas",
    title: "Distribuidoras Suspendidas",
    value: 23,
    change: -8.5,
    icon: "user-x",
    color: "red",
  },
  {
    id: "clientes",
    title: "Clientes Registrados",
    value: "14,872",
    change: 2.1,
    icon: "user-check",
    color: "indigo",
  },
  {
    id: "clientes-nuevos",
    title: "Clientes Nuevos (mes)",
    value: 312,
    change: 15.3,
    icon: "user-plus",
    color: "teal",
  },
  {
    id: "vales-activos",
    title: "Vales Activos",
    value: "9,441",
    change: 3.8,
    icon: "credit-card",
    color: "purple",
  },
  {
    id: "vales-liquidados",
    title: "Vales Liquidados",
    value: "5,128",
    change: 6.7,
    icon: "check-circle",
    color: "green",
  },
  {
    id: "credito-colocado",
    title: "Crédito Colocado",
    value: "4,280,500",
    change: 5.9,
    icon: "trending-up",
    color: "blue",
    prefix: "$",
  },
  {
    id: "credito-disponible",
    title: "Crédito Disponible",
    value: "1,219,500",
    change: -3.2,
    icon: "wallet",
    color: "amber",
    prefix: "$",
  },
  {
    id: "recuperado",
    title: "Total Recuperado",
    value: "3,102,840",
    change: 8.4,
    icon: "arrow-down-circle",
    color: "green",
    prefix: "$",
  },
  {
    id: "morosas",
    title: "Relaciones Morosas",
    value: 187,
    change: -12.1,
    icon: "alert-triangle",
    color: "red",
  },
  {
    id: "solicitudes",
    title: "Solicitudes Pendientes",
    value: 34,
    change: 2.9,
    icon: "inbox",
    color: "amber",
  },
];

// ── Loans Behavior Chart ───────────────────────────────────
export const loanChartData: LoanChartData[] = [
  { mes: "Ene", prestamos: 320000, recuperado: 280000, pendiente: 40000 },
  { mes: "Feb", prestamos: 290000, recuperado: 250000, pendiente: 40000 },
  { mes: "Mar", prestamos: 380000, recuperado: 310000, pendiente: 70000 },
  { mes: "Abr", prestamos: 410000, recuperado: 340000, pendiente: 70000 },
  { mes: "May", prestamos: 360000, recuperado: 300000, pendiente: 60000 },
  { mes: "Jun", prestamos: 430000, recuperado: 380000, pendiente: 50000 },
  { mes: "Jul", prestamos: 480000, recuperado: 400000, pendiente: 80000 },
  { mes: "Ago", prestamos: 520000, recuperado: 430000, pendiente: 90000 },
];

// ── Relations Donut ────────────────────────────────────────
export const relacionDonutData: RelacionDonutData[] = [
  { name: "Pagadas", value: 5128, color: "#22c55e" },
  { name: "Pendientes", value: 3841, color: "#3b82f6" },
  { name: "Morosas", value: 187, color: "#ef4444" },
  { name: "En Conciliación", value: 285, color: "#f59e0b" },
];

// ── Sucursales ─────────────────────────────────────────────
export const sucursalesData: Sucursal[] = [
  {
    id: "s01",
    nombre: "Sucursal Centro",
    gerente: "Lic. Ramón García",
    ciudad: "Ciudad de México",
    distribuidoras: 52,
    clientes: 2840,
    valesActivos: 1820,
    creditoUtilizado: 820000,
    creditoTotal: 1000000,
    porcentajeRecuperacion: 92.4,
    semaforo: "verde",
  },
  {
    id: "s02",
    nombre: "Sucursal Norte",
    gerente: "C.P. María López",
    ciudad: "Monterrey",
    distribuidoras: 38,
    clientes: 2120,
    valesActivos: 1340,
    creditoUtilizado: 610000,
    creditoTotal: 800000,
    porcentajeRecuperacion: 87.6,
    semaforo: "verde",
  },
  {
    id: "s03",
    nombre: "Sucursal Sur",
    gerente: "Lic. Carlos Méndez",
    ciudad: "Guadalajara",
    distribuidoras: 31,
    clientes: 1680,
    valesActivos: 980,
    creditoUtilizado: 430000,
    creditoTotal: 600000,
    porcentajeRecuperacion: 74.2,
    semaforo: "amarillo",
  },
  {
    id: "s04",
    nombre: "Sucursal Oriente",
    gerente: "Ing. Sofía Ruiz",
    ciudad: "Puebla",
    distribuidoras: 28,
    clientes: 1420,
    valesActivos: 860,
    creditoUtilizado: 380000,
    creditoTotal: 500000,
    porcentajeRecuperacion: 68.9,
    semaforo: "amarillo",
  },
  {
    id: "s05",
    nombre: "Sucursal Occidente",
    gerente: "Lic. Roberto Torres",
    ciudad: "León",
    distribuidoras: 19,
    clientes: 820,
    valesActivos: 441,
    creditoUtilizado: 210000,
    creditoTotal: 400000,
    porcentajeRecuperacion: 51.3,
    semaforo: "rojo",
  },
  {
    id: "s06",
    nombre: "Sucursal Bajío",
    gerente: "C.P. Ana Martínez",
    ciudad: "Querétaro",
    distribuidoras: 44,
    clientes: 2280,
    valesActivos: 1560,
    creditoUtilizado: 700000,
    creditoTotal: 900000,
    porcentajeRecuperacion: 88.1,
    semaforo: "verde",
  },
];

// ── Solicitudes Pendientes ─────────────────────────────────
export const solicitudesData: Solicitud[] = [
  {
    id: "SOL-001",
    fecha: "2026-08-03",
    tipo: "Nueva distribuidora",
    solicitante: "Coord. Fernández",
    sucursal: "Sucursal Norte",
    estado: "Pendiente",
    prioridad: "Alta",
  },
  {
    id: "SOL-002",
    fecha: "2026-08-03",
    tipo: "Incremento de crédito",
    solicitante: "Coord. Sánchez",
    sucursal: "Sucursal Centro",
    estado: "En revisión",
    prioridad: "Media",
  },
  {
    id: "SOL-003",
    fecha: "2026-08-02",
    tipo: "Conciliación manual",
    solicitante: "Cajera Gómez",
    sucursal: "Sucursal Sur",
    estado: "Pendiente",
    prioridad: "Alta",
  },
  {
    id: "SOL-004",
    fecha: "2026-08-02",
    tipo: "Cambio de sucursal",
    solicitante: "Distrib. Herrera",
    sucursal: "Sucursal Oriente",
    estado: "Pendiente",
    prioridad: "Baja",
  },
  {
    id: "SOL-005",
    fecha: "2026-08-01",
    tipo: "Edición de información",
    solicitante: "Coord. Vázquez",
    sucursal: "Sucursal Bajío",
    estado: "Pendiente",
    prioridad: "Media",
  },
  {
    id: "SOL-006",
    fecha: "2026-08-01",
    tipo: "Cambio de distribuidora",
    solicitante: "Cliente Ramírez",
    sucursal: "Sucursal Occidente",
    estado: "Pendiente",
    prioridad: "Baja",
  },
];

// ── Alertas ────────────────────────────────────────────────
export const alertasData: AlertItem[] = [
  {
    id: "A01",
    tipo: "error",
    mensaje: "5 distribuidoras con 3 o más relaciones morosas",
    modulo: "Distribuidoras",
    fecha: "2026-08-03",
  },
  {
    id: "A02",
    tipo: "error",
    mensaje: "28 clientes con pagos vencidos > 30 días",
    cantidad: 28,
    modulo: "Clientes",
    fecha: "2026-08-03",
  },
  {
    id: "A03",
    tipo: "warning",
    mensaje: "Sucursal Occidente con crédito agotado al 95%",
    modulo: "Sucursales",
    fecha: "2026-08-03",
  },
  {
    id: "A04",
    tipo: "warning",
    mensaje: "34 solicitudes sin revisar (antiguas > 48 hrs)",
    cantidad: 34,
    modulo: "Solicitudes",
    fecha: "2026-08-02",
  },
  {
    id: "A05",
    tipo: "warning",
    mensaje: "7 distribuidoras sin movimientos en los últimos 30 días",
    cantidad: 7,
    modulo: "Distribuidoras",
    fecha: "2026-08-02",
  },
  {
    id: "A06",
    tipo: "info",
    mensaje: "12 relaciones próximas al vencimiento (< 7 días)",
    cantidad: 12,
    modulo: "Relaciones",
    fecha: "2026-08-03",
  },
  {
    id: "A07",
    tipo: "info",
    mensaje: "Cierre de mes en 3 días — preparar conciliación",
    modulo: "Conciliaciones",
    fecha: "2026-08-03",
  },
];

// ── Distribuidoras Top 10 ──────────────────────────────────
export const top10Distribuidoras: Distribuidor[] = [
  {
    id: "D01",
    nombre: "Distribuidora Estrella",
    sucursal: "Centro",
    colocacion: 184000,
    recuperacion: 172000,
    ganancia: 18200,
    puntos: 4820,
    relaciones: 48,
    morosas: 1,
    porcentajeMora: 2.1,
  },
  {
    id: "D02",
    nombre: "Distrib. Premium Plus",
    sucursal: "Norte",
    colocacion: 162000,
    recuperacion: 154000,
    ganancia: 16400,
    puntos: 4280,
    relaciones: 42,
    morosas: 0,
    porcentajeMora: 0,
  },
  {
    id: "D03",
    nombre: "Distrib. Comercial MX",
    sucursal: "Bajío",
    colocacion: 148000,
    recuperacion: 138000,
    ganancia: 14100,
    puntos: 3920,
    relaciones: 39,
    morosas: 2,
    porcentajeMora: 5.1,
  },
  {
    id: "D04",
    nombre: "Distribuidora del Valle",
    sucursal: "Centro",
    colocacion: 134000,
    recuperacion: 127000,
    ganancia: 13200,
    puntos: 3640,
    relaciones: 35,
    morosas: 1,
    porcentajeMora: 2.9,
  },
  {
    id: "D05",
    nombre: "Distrib. Orgullo Nac.",
    sucursal: "Norte",
    colocacion: 128000,
    recuperacion: 119000,
    ganancia: 11800,
    puntos: 3410,
    relaciones: 33,
    morosas: 0,
    porcentajeMora: 0,
  },
  {
    id: "D06",
    nombre: "Distrib. Éxito Total",
    sucursal: "Bajío",
    colocacion: 121000,
    recuperacion: 112000,
    ganancia: 10900,
    puntos: 3180,
    relaciones: 31,
    morosas: 1,
    porcentajeMora: 3.2,
  },
  {
    id: "D07",
    nombre: "Distrib. Nueva Era",
    sucursal: "Sur",
    colocacion: 118000,
    recuperacion: 108000,
    ganancia: 10200,
    puntos: 2990,
    relaciones: 29,
    morosas: 2,
    porcentajeMora: 6.9,
  },
  {
    id: "D08",
    nombre: "Distrib. Vanguardia",
    sucursal: "Oriente",
    colocacion: 112000,
    recuperacion: 104000,
    ganancia: 9800,
    puntos: 2840,
    relaciones: 28,
    morosas: 0,
    porcentajeMora: 0,
  },
  {
    id: "D09",
    nombre: "Distrib. Calidad Max",
    sucursal: "Centro",
    colocacion: 106000,
    recuperacion: 98000,
    ganancia: 9100,
    puntos: 2680,
    relaciones: 26,
    morosas: 1,
    porcentajeMora: 3.8,
  },
  {
    id: "D10",
    nombre: "Distrib. Confianza",
    sucursal: "Norte",
    colocacion: 98000,
    recuperacion: 91000,
    ganancia: 8400,
    puntos: 2420,
    relaciones: 24,
    morosas: 0,
    porcentajeMora: 0,
  },
];

export const top10Morosas: Distribuidor[] = [
  {
    id: "M01",
    nombre: "Distrib. El Rincón",
    sucursal: "Occidente",
    colocacion: 42000,
    recuperacion: 18000,
    ganancia: 1200,
    puntos: 320,
    relaciones: 12,
    morosas: 8,
    porcentajeMora: 66.7,
  },
  {
    id: "M02",
    nombre: "Distrib. Horizonte",
    sucursal: "Sur",
    colocacion: 38000,
    recuperacion: 19000,
    ganancia: 900,
    puntos: 210,
    relaciones: 10,
    morosas: 6,
    porcentajeMora: 60.0,
  },
  {
    id: "M03",
    nombre: "Distrib. El Portal",
    sucursal: "Oriente",
    colocacion: 31000,
    recuperacion: 14000,
    ganancia: 600,
    puntos: 180,
    relaciones: 8,
    morosas: 5,
    porcentajeMora: 62.5,
  },
  {
    id: "M04",
    nombre: "Distrib. La Colmena",
    sucursal: "Occidente",
    colocacion: 28000,
    recuperacion: 12000,
    ganancia: 400,
    puntos: 140,
    relaciones: 7,
    morosas: 5,
    porcentajeMora: 71.4,
  },
  {
    id: "M05",
    nombre: "Distrib. San Pablo",
    sucursal: "Sur",
    colocacion: 24000,
    recuperacion: 9000,
    ganancia: 200,
    puntos: 80,
    relaciones: 6,
    morosas: 4,
    porcentajeMora: 66.7,
  },
];

// ── Actividad Reciente ─────────────────────────────────────
export const actividadData: ActivityItem[] = [
  {
    id: "ACT01",
    tipo: "registro",
    actor: "Coord. Fernández",
    rolActor: "Coordinador",
    accion: "Registró una nueva distribuidora: Distrib. Promesa",
    fecha: "2026-08-03",
    hora: "18:42",
    icono: "user-plus",
    color: "bg-blue-500",
  },
  {
    id: "ACT02",
    tipo: "autorizacion",
    actor: "Gerente General",
    rolActor: "Gerente",
    accion: "Autorizó incremento de crédito a Distrib. Estrella (+$20,000)",
    fecha: "2026-08-03",
    hora: "17:15",
    icono: "check-circle",
    color: "bg-green-500",
  },
  {
    id: "ACT03",
    tipo: "conciliacion",
    actor: "Cajera Gómez",
    rolActor: "Cajera",
    accion: "Realizó conciliación manual — Sucursal Sur",
    fecha: "2026-08-03",
    hora: "16:30",
    icono: "refresh-cw",
    color: "bg-purple-500",
  },
  {
    id: "ACT04",
    tipo: "liquidacion",
    actor: "Cliente Martínez",
    rolActor: "Cliente",
    accion: "Liquidó vale #VAL-8821 — $3,400",
    fecha: "2026-08-03",
    hora: "15:12",
    icono: "dollar-sign",
    color: "bg-green-500",
  },
  {
    id: "ACT05",
    tipo: "visita",
    actor: "Verif. Herrera",
    rolActor: "Verificador",
    accion: "Aprobó visita de campo — Distrib. Del Valle",
    fecha: "2026-08-03",
    hora: "14:45",
    icono: "map-pin",
    color: "bg-amber-500",
  },
  {
    id: "ACT06",
    tipo: "suspension",
    actor: "Coord. Vázquez",
    rolActor: "Coordinador",
    accion: "Suspendió distribuidora: Distrib. El Rincón (mora excesiva)",
    fecha: "2026-08-03",
    hora: "13:20",
    icono: "alert-triangle",
    color: "bg-red-500",
  },
  {
    id: "ACT07",
    tipo: "registro",
    actor: "Coord. Sánchez",
    rolActor: "Coordinador",
    accion: "Registró 14 nuevos clientes en Sucursal Centro",
    fecha: "2026-08-03",
    hora: "11:08",
    icono: "users",
    color: "bg-indigo-500",
  },
  {
    id: "ACT08",
    tipo: "incremento",
    actor: "Gerente General",
    rolActor: "Gerente",
    accion: "Aprobó límite de crédito global Sucursal Bajío (+$100,000)",
    fecha: "2026-08-02",
    hora: "19:00",
    icono: "trending-up",
    color: "bg-teal-500",
  },
];

// ── Notificaciones Navbar ──────────────────────────────────
export const notificacionesData: NavNotification[] = [
  {
    id: "N01",
    mensaje: "34 solicitudes pendientes de revisión",
    tiempo: "hace 5 min",
    leida: false,
    tipo: "solicitud",
  },
  {
    id: "N02",
    mensaje: "Sucursal Occidente alcanzó 95% de crédito",
    tiempo: "hace 22 min",
    leida: false,
    tipo: "alerta",
  },
  {
    id: "N03",
    mensaje: "Conciliación de Cajera Gómez requiere aprobación",
    tiempo: "hace 1 hr",
    leida: false,
    tipo: "solicitud",
  },
  {
    id: "N04",
    mensaje: "Informe mensual generado exitosamente",
    tiempo: "hace 3 hrs",
    leida: true,
    tipo: "info",
  },
];

// ── Panel Financiero ───────────────────────────────────────
export const panelFinanciero = {
  creditoTotalOtorgado: 5500000,
  creditoDisponible: 1219500,
  capitalRecuperado: 3102840,
  capitalPendiente: 1177160,
  gananciasMes: 284200,
  gananciasAnio: 2140800,
  montoEnMora: 384500,
  montoRecuperadoHoy: 48200,
};
